set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'php.vim'
Plugin 'joonty/vdebug'
Plugin 'shawncplus/phpcomplete.vim'
Plugin 'ervandew/supertab'
Plugin 'kien/ctrlp.vim'
"Plugin 'joonty/vim-phpqa'
Plugin 'majutsushi/tagbar'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/syntastic'

call vundle#end()

filetype plugin indent on
let g:SuperTabDefaultCompletionType = ""
set tags=~/ua/uaweb/magento/magento-php.tags
let g:tagcommands = {
\    "php" : {
\        "tagfile" : "~/ua/uaweb/magento/.php.tags",
\        "args" : "-R",
\        "files" : "~/ua/uaweb/magento/**"
\    }
\}
let g:tagbar_autofocus = 1

"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_php_phpcs_quiet_messages = {
    \ "type": "style",
    \ "regex": ['Short PHP opening tag used with echo'] }

" NERDTree
map <Leader>n :NERDTreeToggle<CR>

" phpqa
let g:phpqa_codesniffer_autorun = 0
let g:phpqa_messdetector_autorun = 0

" Vdebug
" let g:vdebug_options["path_maps"] = {"/opt/ua/www": "/Users/jdodge/ua/uaweb/magento",}
"let g:vdebug_options = {"path_maps": {"/opt/ua/www": "/Users/jdodge/ua/uaweb/magento",}}

let g:vdebug_options= {
    \    "port" : 9000,
    \    "server" : '',
    \    "timeout" : 20,
    \    "on_close" : 'detach',
    \    "break_on_open" : 0,
    \    "ide_key" : '',
    \    "path_maps" : {"/opt/ua/www": "/Users/jdodge/ua/uaweb/magento",},
    \    "debug_window_level" : 0,
    \    "debug_file_level" : 0,
    \    "debug_file" : "",
    \    "watch_window_style" : 'expanded',
    \    "marker_default" : '⬦',
    \    "marker_closed_tree" : '▸',
    \    "marker_open_tree" : '▾',
    \    "continuous_mode" : 1
    \}

let g:ctrlp_custom_ignore = {'dir':'magento\/htdocs\/lib\/vendor$|\.git$|\.hg$|\.svn$'}

let g:ctrlp_max_files = 0  " unlimited
let g:ctrlp_max_depth = 100
let g:ctrlp_follow_symlinks = 1

map <Leader>s : vsp %:p:h <CR>
map <Leader>v : source ~/.vimrc <CR>
map <Leader>r : res +44 <CR>
map <Leader>b :TagbarToggle <CR>
map <C-f> :set noea <CR> :set ea <CR>
map <C-i>p :set paste <CR> i
map <C-i>n :set nopaste <CR> i
map <Left> <C-W>h
map <Right> <C-W>l
map <Up> <C-W>k
map <Down> <C-W>j
map <F4> :set textwidth=0 <CR>
syntax enable

" IDE settings
set softtabstop=4
set shiftwidth=4
set expandtab
set hlsearch
set laststatus=2
set ruler
autocmd BufWritePre *.p* :%s/\s\+$//e
autocmd QuickFixCmdPost *grep* cwindow
